In [75]:
### ALEXANDRO JESUS CERON AVILES  9D IDGS
### EXAMEN DE UNIDAD 2

In [76]:
import pandas as pd
import numpy as np

In [77]:
# 1.- Crear dataframe
registros = [[101, 'Electrónica', 1500.0, 10, 120],
             [102, 'Ropa', pd.NA, 15, 85],
             [103, 'Hogar', 350.0, 0, 200],
             [104, 'Electrónica', 2100.0, 20, 150],
             [105, 'Ropa', 450.0, 5, 90],
             [106, 'Hogar', pd.NA, 10, 180],
             [107, 'Electrónica', 1800.0, 15, 135],
             [108, 'Ropa', 500.0, 0, 95],
             ]
df = pd.DataFrame(registros, columns=['id_producto', 'categoria', 'precio', 'descuento', 'unidades_vendidas'])
df

   id_producto    categoria  precio  descuento  unidades_vendidas
0          101  Electrónica  1500.0         10                120
1          102         Ropa    <NA>         15                 85
2          103        Hogar   350.0          0                200
3          104  Electrónica  2100.0         20                150
4          105         Ropa   450.0          5                 90
5          106        Hogar    <NA>         10                180
6          107  Electrónica  1800.0         15                135
7          108         Ropa   500.0          0                 95

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_producto        8 non-null      int64
 1   categoria          8 non-null      object
 2   precio             6 non-null      object
 3   descuento          8 non-null      int64
 4   unidades_vendidas  8 non-null      int64
dtypes: int64(3), object(2)
memory usage: 452.0+ bytes

In [79]:
# 2. Crear df_filtrado
condicion_categoria = (df['categoria'].isin(['Electrónica']))
condicion_descuento = (df['descuento'].astype(float) >= 10.0)
df_filtrado = df[condicion_categoria & condicion_descuento]
df_filtrado

   id_producto    categoria  precio  descuento  unidades_vendidas
0          101  Electrónica  1500.0         10                120
3          104  Electrónica  2100.0         20                150
6          107  Electrónica  1800.0         15                135

In [80]:
# 3.- Remplazar valores nulos

df_Electrónica = df[df['categoria'] == 'Electrónica']
moda_Electrónica = df['precio'].median()

df_Ropa = df[df['categoria'] == 'Ropa']
moda_Ropa = df['precio'].median()

df_Hogar = df[df['categoria'] == 'Hogar']
moda_Hogar = df['precio'].median()

"""
# Rellenado
for i, registro in df.iterrows():
  if registro['categoria'] == 'Electrónica' and registro['precio'].isna():
    df.iloc[i, ['precio'].astype(float)] = moda_Electrónica

  if registro['categoria'] == 'Ropa' and registro['precio'].isnull():
    df.iloc[i, ['precio']] = moda_Ropa

  if registro['categoria'] == 'Hogar' and registro['precio'].isnull():
    df.iloc[i, ['precio']] = moda_Hogar

df
"""
"""
df['precio'] = np.where(df['categoria'] == 'Electrónica' and df['precio'] == pd.NA, moda_Electrónica)
df['precio'] = np.where(df['categoria'] == 'Ropa' and df['precio'].empty(), moda_Ropa)
df['precio'] = np.where(df['categoria'] == 'Electrónica' and df['precio'].empty(), moda_Hogar)
"""

df.loc[df['id_producto'] == 102, ['precio']] = moda_Ropa
df.loc[df['id_producto'] == 106, ['precio']] = moda_Hogar
df

   id_producto    categoria  precio  descuento  unidades_vendidas
0          101  Electrónica  1500.0         10                120
1          102         Ropa  1000.0         15                 85
2          103        Hogar   350.0          0                200
3          104  Electrónica  2100.0         20                150
4          105         Ropa   450.0          5                 90
5          106        Hogar  1000.0         10                180
6          107  Electrónica  1800.0         15                135
7          108         Ropa   500.0          0                 95

In [81]:
# 4.- Crear nueva columna
df['precio_final'] = df['precio'] * ( 1 - (df['descuento'] / 100))
df

   id_producto    categoria  precio  descuento  unidades_vendidas precio_final
0          101  Electrónica  1500.0         10                120       1350.0
1          102         Ropa  1000.0         15                 85        850.0
2          103        Hogar   350.0          0                200        350.0
3          104  Electrónica  2100.0         20                150       1680.0
4          105         Ropa   450.0          5                 90        427.5
5          106        Hogar  1000.0         10                180        900.0
6          107  Electrónica  1800.0         15                135       1530.0
7          108         Ropa   500.0          0                 95        500.0