In [2]:
# pip install pandas

Requirement already satisfied: pandas in C:\Users\CC6\anaconda3\envs\prueba9d\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\CC6\anaconda3\envs\prueba9d\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\CC6\anaconda3\envs\prueba9d\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\CC6\anaconda3\envs\prueba9d\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\CC6\anaconda3\envs\prueba9d\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd

In [11]:
df = pd.read_csv('AB_NYC_2019.csv') # leer un archivo csv

In [8]:
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [10]:
df.info() # Detalles del dataframe

<class 'pandas.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  str
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  str
 4   neighbourhood_group             48895 non-null  str
 5   neighbourhood                   48895 non-null  str
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  str
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  str
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), str(6)
memory usage: 6.0 MB

Describe sirve para ...

In [14]:
df.describe() # Devuelve las variables basicas y estadisticas

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [17]:
df.shape # Devuelve numero de registros y columnas

(48895, 16)

Si es uno solo, solo van corchetes, pero si son mas, entonces van dos corchetes para indicar la lista

In [22]:
df[['name', 'price']]

                                                    name  price
0                     Clean & quiet apt home by the park    149
1                                  Skylit Midtown Castle    225
2                    THE VILLAGE OF HARLEM....NEW YORK !    150
3                        Cozy Entire Floor of Brownstone     89
4       Entire Apt: Spacious Studio/Loft by central park     80
...                                                  ...    ...
48890    Charming one bedroom - newly renovated rowhouse     70
48891      Affordable room in Bushwick/East Williamsburg     40
48892            Sunny Studio at Historical Neighborhood    115
48893               43rd St. Time Square-cozy single bed     55
48894  Trendy duplex in the very heart of Hell's Kitchen     90

[48895 rows x 2 columns]

In [24]:
df[df['price']>300] # Condicion para la columna price

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
61,15396,Sunny & Spacious Chelsea Apartment,60278,Petra,Manhattan,Chelsea,40.74623,-73.99530,Entire home/apt,375,180,5,2018-11-03,0.12,1,180
85,19601,perfect for a family or small group,74303,Maggie,Brooklyn,Brooklyn Heights,40.69723,-73.99268,Entire home/apt,800,1,25,2016-08-04,0.24,1,7
103,23686,2000 SF 3br 2bath West Village private townhouse,93790,Ann,Manhattan,West Village,40.73096,-74.00319,Entire home/apt,500,4,46,2019-05-18,0.55,2,243
114,26933,2 BR / 2 Bath Duplex Apt with patio! East Village,72062,Bruce,Manhattan,East Village,40.72540,-73.98157,Entire home/apt,350,2,7,2017-08-09,0.06,4,298
116,26969,2 story family home in Williamsburg,115307,Alexandra,Brooklyn,Williamsburg,40.71942,-73.95748,Entire home/apt,325,3,324,2019-06-23,3.01,1,107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48758,36420289,"Rustic Garden House Apt, 2 stops from Manhattan",73211393,LaGabrell,Queens,Long Island City,40.75508,-73.93258,Entire home/apt,350,2,0,NaN,NaN,1,364
48833,36450896,Brand New 3-Bed Apt in the Best Location of FiDi,29741813,Yue,Manhattan,Financial District,40.70605,-74.01042,Entire home/apt,475,2,0,NaN,NaN,1,64
48839,36452721,Massage Spa. Stay overnight. Authors Artist dr...,274079964,Richard,Brooklyn,Sheepshead Bay,40.59866,-73.95661,Private room,800,1,0,NaN,NaN,1,23
48842,36453160,LUXURY MANHATTAN PENTHOUSE+HUDSON RIVER+EMPIRE...,224171371,LuxuryApartmentsByAmber,Manhattan,Chelsea,40.75204,-74.00292,Entire home/apt,350,1,0,NaN,NaN,1,9
48856,36457700,"Large 3 bed, 2 bath , garden , bbq , all you need",66993395,Thomas,Brooklyn,Bedford-Stuyvesant,40.68886,-73.92879,Entire home/apt,345,4,0,NaN,NaN,3,354

Instalar librería para leer archivos excel viejos

In [26]:
!pip install xlrd openpyxl

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: xlrd, et-xmlfile, openpyxl

   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   ---------------------------------------- 3/3 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5 xlrd-2.0.2

In [29]:
df_investigadores = pd.read_excel('investigadores.xls')

In [30]:
df_investigadores

   Temperatura(°C)  Eficiencia (%)
0               20              30
1               25              34
2               30              39
3               35              42
4               40              46
5               45              49
6               50              51

In [32]:
df_ventas = pd.read_excel('ventas_electronicas.xlsx')

In [33]:
df_ventas  # Muestra solo de la primera pagina

,Producto,Marca,Modelo,Precio,Cantidad,Fecha_Venta,Vendedor,Region,Descuento,Categoria
0,OnePlus 9,OnePlus,OnePlus 9 875,1932.75,4,2024-12-09,Elena,Norte,0.04,Gama alta
1,Pixel 6,Lenovo,Pixel 6 113,1253.10,7,2025-03-20,María,Sur,0.13,Gama baja
2,iPhone 13,Samsung,iPhone 13 373,1101.68,2,2025-03-12,María,Sur,0.25,Gama alta
3,OnePlus 9,Asus,OnePlus 9 743,1249.52,1,2024-07-10,Juan,Este,0.28,Gama media
4,Galaxy S21,Dell,Galaxy S21 501,620.14,1,2025-03-10,Carlos,Este,0.23,Gama baja
5,Pixel 6,Apple,Pixel 6 781,576.47,5,2024-10-05,Carlos,Sur,0.19,Gama media
6,Galaxy S21,Xiaomi,Galaxy S21 513,851.78,3,2025-01-06,Ana,Norte,0.29,Gama media
7,Pixel 6,Google,Pixel 6 825,455.12,10,2025-03-25,María,Este,0.22,Gama baja
8,Pixel 6,Sony,Pixel 6 916,1109.73,8,2024-12-14,Carlos,Norte,0.09,Gama alta
9,iPhone 13,Sony,iPhone 13 417,56.42,8,2025-06-15,Ana,Norte,0.23,Gama alta
10,Pixel 6,Google,Pixel 6 641,1394.96,10,2025-02-07,Juan,Sur,0.23,Gama baja
11,Pixel 6,Xiaomi,Pixel 6 908,1227.69,3,2025-06-14,María,Norte,0.00,Gama media
12,OnePlus 9,Google,OnePlus 9 275,1442.39,8,2024-12-15,Juan,Oeste,0.19,Gama media
13,OnePlus 9,HP,OnePlus 9 149,1126.55,2,2024-12-09,Juan,Norte,0.15,Gama baja
14,Pixel 6,Xiaomi,Pixel 6 394,67.01,5,2024-07-16,Luis,Norte,0.01,Gama media
15,Galaxy S21,Sony,Galaxy S21 849,146.68,6,2025-01-12,Juan,Oeste,0.17,Gama alta
16,Pixel 6,Apple,Pixel 6 631,1003.15,1,2025-05-10,María,Oeste,0.16,Gama alta
17,Pixel 6,Dell,Pixel 6 617,256.29,7,2025-04-04,Ana,Oeste,0.28,Gama alta
18,Pixel 6,HP,Pixel 6 390,1430.86,1,2024-10-07,Carlos,Norte,0.16,Gama alta
19,Pixel 6,Lenovo,Pixel 6 662,778.65,4,2024-11-16,Juan,Oeste,0.25,Gama alta
20,iPhone 13,Apple,iPhone 13 230,1078.16,10,2025-06-20,María,Norte,0.09,Gama baja
21,iPhone 13,Lenovo,iPhone 13 699,1133.94,10,2024-10-23,Laura,Este,0.03,Gama baja
22,Xiaomi 12,Xiaomi,Xiaomi 12 863,1756.75,5,2024-08-15,Luis,Este,0.17,Gama alta
23,Pixel 6,OnePlus,Pixel 6 927,220.09,5,2024-07-23,Elena,Norte,0.19,Gama baja
24,Galaxy S21,Apple,Galaxy S21 438,1024.37,2,2025-04-26,Elena,Norte,0.08,Gama media
25,Pixel 6,Asus,Pixel 6 198,644.80,9,2024-08-19,María,Sur,0.07,Gama alta
26,Pixel 6,Samsung,Pixel 6 338,842.19,3,2025-01-04,Carlos,Este,0.01,Gama media
27,Galaxy S21,Asus,Galaxy S21 327,1806.63,3,2025-02-03,Ana,Este,0.25,Gama baja
28,Pixel 6,HP,Pixel 6 460,1445.69,3,2025-03-12,Laura,Norte,0.12,Gama media
29,Xiaomi 12,Lenovo,Xiaomi 12 994,140.67,6,2025-01-02,Elena,Sur,0.12,Gama baja

In [34]:
df_laptos = pd.read_excel('ventas_electronicas.xlsx', sheet_name='Laptops') # Se trae la pagina de nombre datos

In [35]:
df_laptos

,Producto,Marca,Modelo,Precio,Cantidad,Fecha_Venta,Vendedor,Region,Descuento,Categoria
0,Dell XPS,Dell,Dell XPS 252,1496.85,3,2024-10-27,Luis,Sur,0.29,Oficina
1,Dell XPS,Google,Dell XPS 404,293.58,10,2025-01-09,Elena,Oeste,0.17,Oficina
2,HP Spectre,HP,HP Spectre 553,90.28,4,2024-12-20,María,Este,0.10,Gaming
3,Lenovo ThinkPad,Apple,Lenovo ThinkPad 116,1373.63,8,2024-12-31,Juan,Oeste,0.05,Oficina
4,Lenovo ThinkPad,Xiaomi,Lenovo ThinkPad 182,1815.88,8,2024-10-27,Juan,Oeste,0.25,Ultrabook
5,Lenovo ThinkPad,Lenovo,Lenovo ThinkPad 763,438.14,8,2025-02-14,Ana,Norte,0.08,Gaming
6,Lenovo ThinkPad,Lenovo,Lenovo ThinkPad 794,1902.15,4,2024-08-17,Luis,Oeste,0.22,Gaming
7,HP Spectre,Xiaomi,HP Spectre 270,1267.88,3,2024-08-29,María,Sur,0.15,Gaming
8,MacBook Air,Dell,MacBook Air 452,1365.76,6,2024-09-26,María,Oeste,0.25,Oficina
9,Lenovo ThinkPad,Dell,Lenovo ThinkPad 610,390.10,1,2025-03-02,Luis,Este,0.28,Ultrabook
10,Asus ZenBook,Lenovo,Asus ZenBook 964,952.32,8,2024-11-05,María,Este,0.02,Ultrabook
11,HP Spectre,HP,HP Spectre 357,1858.03,5,2025-05-19,Luis,Norte,0.15,Oficina
12,Dell XPS,OnePlus,Dell XPS 472,1435.84,10,2024-12-14,Diego,Norte,0.17,Oficina
13,MacBook Air,Lenovo,MacBook Air 590,112.26,3,2025-04-05,Juan,Sur,0.25,Gaming
14,Lenovo ThinkPad,Sony,Lenovo ThinkPad 857,392.24,7,2025-01-24,Juan,Este,0.09,Oficina
15,Asus ZenBook,Samsung,Asus ZenBook 179,1603.02,3,2025-01-29,Laura,Este,0.05,Ultrabook
16,Asus ZenBook,Google,Asus ZenBook 630,759.14,9,2025-01-12,Luis,Norte,0.10,Oficina
17,Lenovo ThinkPad,Sony,Lenovo ThinkPad 856,382.91,6,2025-04-08,Ana,Este,0.19,Gaming
18,Asus ZenBook,Xiaomi,Asus ZenBook 159,980.60,10,2025-03-11,Elena,Sur,0.01,Ultrabook
19,Asus ZenBook,Apple,Asus ZenBook 748,888.89,2,2025-06-15,Carlos,Este,0.27,Gaming
20,Lenovo ThinkPad,HP,Lenovo ThinkPad 132,616.46,5,2025-05-30,María,Norte,0.24,Gaming
21,MacBook Air,Samsung,MacBook Air 523,1572.26,1,2024-11-02,María,Norte,0.16,Ultrabook
22,MacBook Air,Asus,MacBook Air 148,1071.32,3,2025-04-03,Ana,Sur,0.17,Oficina
23,HP Spectre,OnePlus,HP Spectre 284,449.60,4,2025-02-23,Diego,Oeste,0.25,Gaming
24,MacBook Air,Xiaomi,MacBook Air 662,711.55,5,2025-03-26,Luis,Norte,0.28,Ultrabook
25,Dell XPS,Samsung,Dell XPS 937,1473.60,7,2025-03-02,Elena,Este,0.11,Gaming
26,MacBook Air,Lenovo,MacBook Air 165,612.07,3,2025-03-10,María,Este,0.18,Ultrabook
27,Dell XPS,HP,Dell XPS 523,376.86,8,2024-08-09,Luis,Sur,0.25,Ultrabook
28,Asus ZenBook,Sony,Asus ZenBook 391,455.80,6,2025-01-01,María,Oeste,0.06,Ultrabook
29,HP Spectre,HP,HP Spectre 198,818.22,4,2024-07-16,Luis,Este,0.23,Oficina

Con esto ahora ventas es una coleccion de dataframe, osea un diccionario

In [37]:
df_ventas = pd.read_excel('ventas_electronicas.xlsx', sheet_name=None) # Se trae todas las paginas

In [39]:
df_ventas['Tablets']  # Se trae la pagina en concreto de Tablets

,Producto,Marca,Modelo,Precio,Cantidad,Fecha_Venta,Vendedor,Region,Descuento,Categoria
0,iPad Pro,Asus,iPad Pro 249,1462.12,2,2024-10-12,Elena,Norte,0.03,Pro
1,Lenovo Tab,Lenovo,Lenovo Tab 362,1941.88,9,2024-10-29,Diego,Sur,0.13,Pro
2,Lenovo Tab,Xiaomi,Lenovo Tab 173,1148.47,2,2024-10-01,Luis,Sur,0.23,Estudiante
3,Lenovo Tab,Lenovo,Lenovo Tab 609,85.10,4,2025-04-01,Elena,Oeste,0.08,Pro
4,Amazon Fire,Xiaomi,Amazon Fire 318,1853.81,3,2025-02-09,Elena,Oeste,0.13,Estudiante
5,Galaxy Tab,Apple,Galaxy Tab 788,773.15,5,2024-09-04,Luis,Oeste,0.13,Pro
6,Surface Go,Dell,Surface Go 508,1579.73,4,2025-01-05,Luis,Sur,0.25,Estudiante
7,Lenovo Tab,OnePlus,Lenovo Tab 773,447.57,6,2025-03-04,Juan,Norte,0.14,Niños
8,Surface Go,Xiaomi,Surface Go 758,1261.04,1,2024-11-26,Juan,Este,0.10,Estudiante
9,Surface Go,Apple,Surface Go 764,306.04,4,2025-03-15,María,Norte,0.09,Niños
10,iPad Pro,Dell,iPad Pro 565,773.47,2,2024-10-23,Ana,Oeste,0.29,Estudiante
11,Amazon Fire,Dell,Amazon Fire 704,188.79,4,2024-08-14,Juan,Este,0.18,Niños
12,Lenovo Tab,Xiaomi,Lenovo Tab 164,340.29,9,2025-04-03,Laura,Oeste,0.18,Estudiante
13,Lenovo Tab,Sony,Lenovo Tab 292,1038.44,7,2024-12-10,Juan,Sur,0.22,Estudiante
14,Galaxy Tab,Samsung,Galaxy Tab 424,1385.63,1,2025-06-26,María,Sur,0.18,Niños
15,Surface Go,Google,Surface Go 906,421.44,4,2025-02-28,Carlos,Oeste,0.04,Estudiante
16,Lenovo Tab,Asus,Lenovo Tab 541,1111.94,5,2025-06-22,Ana,Norte,0.03,Estudiante
17,Surface Go,Xiaomi,Surface Go 744,308.15,2,2024-07-07,María,Este,0.27,Niños
18,Amazon Fire,HP,Amazon Fire 513,1696.59,9,2025-03-26,Luis,Oeste,0.07,Estudiante
19,Lenovo Tab,Asus,Lenovo Tab 528,1755.89,4,2024-12-13,Elena,Sur,0.23,Niños
20,Galaxy Tab,OnePlus,Galaxy Tab 312,830.98,5,2025-06-08,María,Sur,0.04,Pro
21,Galaxy Tab,Apple,Galaxy Tab 168,1544.71,1,2025-01-25,Ana,Norte,0.24,Estudiante
22,iPad Pro,Xiaomi,iPad Pro 697,919.81,7,2025-04-01,Ana,Sur,0.12,Estudiante
23,Lenovo Tab,Xiaomi,Lenovo Tab 636,802.90,10,2025-01-23,Diego,Norte,0.04,Estudiante
24,Amazon Fire,Lenovo,Amazon Fire 779,1724.45,5,2025-04-23,Juan,Norte,0.24,Estudiante
25,Surface Go,Xiaomi,Surface Go 740,713.55,4,2025-05-31,Ana,Norte,0.22,Estudiante
26,Galaxy Tab,Asus,Galaxy Tab 298,1154.91,1,2024-11-26,Elena,Oeste,0.27,Niños
27,Surface Go,Lenovo,Surface Go 626,1307.29,10,2025-03-10,Carlos,Oeste,0.16,Pro
28,iPad Pro,Lenovo,iPad Pro 247,746.14,8,2024-12-11,Juan,Oeste,0.13,Pro
29,iPad Pro,HP,iPad Pro 202,1746.27,6,2025-04-20,Laura,Este,0.22,Pro

NOTA: SI PUEDE LEER FORMULAS

Pedir solo ciertas columnas a una pagina

In [40]:
df_accesorios = pd.read_excel('ventas_electronicas.xlsx', sheet_name='Accesorios', usecols='A:D, G')

In [41]:
df_accesorios

      Producto    Marca          Modelo   Precio Vendedor
0   Power Bank     Dell  Power Bank 438   195.06    María
1     Cargador  Samsung    Cargador 607  1113.03      Ana
2     Cargador   Lenovo    Cargador 654   790.11   Carlos
3        Funda       HP       Funda 199   944.47    Laura
4     Cargador     Asus    Cargador 986  1426.40     Juan
5        Funda   Lenovo       Funda 405   322.49     Luis
6    Audífonos    Apple   Audífonos 380   597.61     Luis
7    Audífonos     Dell   Audífonos 314   185.42    María
8        Funda   Lenovo       Funda 758  1238.68   Carlos
9    Audífonos  OnePlus   Audífonos 925  1708.63     Luis
10   Audífonos     Dell   Audífonos 187   495.59    Elena
11       Funda   Google       Funda 270  1430.31     Juan
12  Power Bank   Lenovo  Power Bank 976   598.54     Juan
13   Cable USB   Google   Cable USB 561   429.22      Ana
14   Audífonos     Sony   Audífonos 269   311.14     Juan
15  Power Bank   Google  Power Bank 269   960.35   Carlos
16  Power Bank  Samsung  Power Bank 180   851.99    Elena
17    Cargador    Apple    Cargador 381   181.68      Ana
18  Power Bank     Sony  Power Bank 709  1174.38    María
19   Audífonos    Apple   Audífonos 493   903.77      Ana
20  Power Bank     Dell  Power Bank 855   496.20   Carlos
21       Funda  OnePlus       Funda 144  1320.29   Carlos
22       Funda   Lenovo       Funda 568   115.89    Laura
23    Cargador     Dell    Cargador 338  1062.97    Elena
24   Cable USB       HP   Cable USB 451   595.52     Luis
25       Funda   Lenovo       Funda 348   667.33    Diego
26       Funda     Dell       Funda 270   578.78      Ana
27       Funda     Sony       Funda 521   863.90     Juan
28  Power Bank     Asus  Power Bank 808  1021.29     Juan
29    Cargador     Asus    Cargador 827  1712.48    Diego

Si se salta 5 columnas, va a tomar el primer registro que encuentre como encabezado

In [42]:
df_accesorios = pd.read_excel('ventas_electronicas.xlsx', sheet_name='Accesorios', skiprows=5)

In [43]:
df_accesorios

,Cargador,Asus,Cargador 986,1426.4,6,2024-09-07 00:00:00,Juan,Norte,0.11,Protección
0,Funda,Lenovo,Funda 405,322.49,1,2025-03-29,Luis,Este,0.20,Audio
1,Audífonos,Apple,Audífonos 380,597.61,8,2025-01-26,Luis,Sur,0.13,Carga
2,Audífonos,Dell,Audífonos 314,185.42,8,2025-02-01,María,Este,0.08,Protección
3,Funda,Lenovo,Funda 758,1238.68,1,2025-04-21,Carlos,Este,0.22,Audio
4,Audífonos,OnePlus,Audífonos 925,1708.63,9,2025-03-02,Luis,Este,0.01,Audio
5,Audífonos,Dell,Audífonos 187,495.59,1,2025-06-01,Elena,Oeste,0.10,Protección
6,Funda,Google,Funda 270,1430.31,6,2025-01-27,Juan,Oeste,0.18,Audio
7,Power Bank,Lenovo,Power Bank 976,598.54,10,2025-01-16,Juan,Oeste,0.20,Carga
8,Cable USB,Google,Cable USB 561,429.22,10,2024-07-25,Ana,Oeste,0.13,Audio
9,Audífonos,Sony,Audífonos 269,311.14,5,2025-04-22,Juan,Este,0.09,Audio
10,Power Bank,Google,Power Bank 269,960.35,6,2024-08-27,Carlos,Oeste,0.25,Audio
11,Power Bank,Samsung,Power Bank 180,851.99,8,2024-10-13,Elena,Norte,0.20,Carga
12,Cargador,Apple,Cargador 381,181.68,5,2025-05-21,Ana,Este,0.08,Protección
13,Power Bank,Sony,Power Bank 709,1174.38,5,2024-10-09,María,Sur,0.29,Audio
14,Audífonos,Apple,Audífonos 493,903.77,4,2025-02-04,Ana,Este,0.12,Carga
15,Power Bank,Dell,Power Bank 855,496.20,6,2025-01-14,Carlos,Oeste,0.18,Protección
16,Funda,OnePlus,Funda 144,1320.29,3,2025-01-10,Carlos,Sur,0.24,Protección
17,Funda,Lenovo,Funda 568,115.89,6,2025-04-16,Laura,Oeste,0.17,Carga
18,Cargador,Dell,Cargador 338,1062.97,4,2025-01-18,Elena,Este,0.04,Conectividad
19,Cable USB,HP,Cable USB 451,595.52,3,2025-01-16,Luis,Sur,0.12,Protección
20,Funda,Lenovo,Funda 348,667.33,1,2024-11-26,Diego,Norte,0.10,Conectividad
21,Funda,Dell,Funda 270,578.78,9,2025-04-13,Ana,Norte,0.07,Protección
22,Funda,Sony,Funda 521,863.90,4,2024-08-15,Juan,Oeste,0.09,Audio
23,Power Bank,Asus,Power Bank 808,1021.29,5,2024-09-17,Juan,Este,0.13,Audio
24,Cargador,Asus,Cargador 827,1712.48,6,2025-01-30,Diego,Este,0.21,Protección