In [1]:
import pandas as pd

In [25]:
df_airbnb = pd.read_csv('AB_NYC_2019.csv')

In [3]:
df_laptops = pd.read_excel('ventas_electronicas.xlsx', sheet_name='Laptops')

CONDICIONALES

In [6]:
#Ventas de laptops de la región Norte
df_laptops[df_laptops['Region'] == 'Norte']

,Producto,Marca,Modelo,Precio,Cantidad,Fecha_Venta,Vendedor,Region,Descuento,Categoria
5,Lenovo ThinkPad,Lenovo,Lenovo ThinkPad 763,438.14,8,2025-02-14,Ana,Norte,0.08,Gaming
11,HP Spectre,HP,HP Spectre 357,1858.03,5,2025-05-19,Luis,Norte,0.15,Oficina
12,Dell XPS,OnePlus,Dell XPS 472,1435.84,10,2024-12-14,Diego,Norte,0.17,Oficina
16,Asus ZenBook,Google,Asus ZenBook 630,759.14,9,2025-01-12,Luis,Norte,0.10,Oficina
20,Lenovo ThinkPad,HP,Lenovo ThinkPad 132,616.46,5,2025-05-30,María,Norte,0.24,Gaming
21,MacBook Air,Samsung,MacBook Air 523,1572.26,1,2024-11-02,María,Norte,0.16,Ultrabook
24,MacBook Air,Xiaomi,MacBook Air 662,711.55,5,2025-03-26,Luis,Norte,0.28,Ultrabook

In [7]:
# Ventas cuyo precio sea mayor a 600
df_laptops[df_laptops['Precio'] > 600]

,Producto,Marca,Modelo,Precio,Cantidad,Fecha_Venta,Vendedor,Region,Descuento,Categoria
0,Dell XPS,Dell,Dell XPS 252,1496.85,3,2024-10-27,Luis,Sur,0.29,Oficina
3,Lenovo ThinkPad,Apple,Lenovo ThinkPad 116,1373.63,8,2024-12-31,Juan,Oeste,0.05,Oficina
4,Lenovo ThinkPad,Xiaomi,Lenovo ThinkPad 182,1815.88,8,2024-10-27,Juan,Oeste,0.25,Ultrabook
6,Lenovo ThinkPad,Lenovo,Lenovo ThinkPad 794,1902.15,4,2024-08-17,Luis,Oeste,0.22,Gaming
7,HP Spectre,Xiaomi,HP Spectre 270,1267.88,3,2024-08-29,María,Sur,0.15,Gaming
8,MacBook Air,Dell,MacBook Air 452,1365.76,6,2024-09-26,María,Oeste,0.25,Oficina
10,Asus ZenBook,Lenovo,Asus ZenBook 964,952.32,8,2024-11-05,María,Este,0.02,Ultrabook
11,HP Spectre,HP,HP Spectre 357,1858.03,5,2025-05-19,Luis,Norte,0.15,Oficina
12,Dell XPS,OnePlus,Dell XPS 472,1435.84,10,2024-12-14,Diego,Norte,0.17,Oficina
15,Asus ZenBook,Samsung,Asus ZenBook 179,1603.02,3,2025-01-29,Laura,Este,0.05,Ultrabook
16,Asus ZenBook,Google,Asus ZenBook 630,759.14,9,2025-01-12,Luis,Norte,0.10,Oficina
18,Asus ZenBook,Xiaomi,Asus ZenBook 159,980.60,10,2025-03-11,Elena,Sur,0.01,Ultrabook
19,Asus ZenBook,Apple,Asus ZenBook 748,888.89,2,2025-06-15,Carlos,Este,0.27,Gaming
20,Lenovo ThinkPad,HP,Lenovo ThinkPad 132,616.46,5,2025-05-30,María,Norte,0.24,Gaming
21,MacBook Air,Samsung,MacBook Air 523,1572.26,1,2024-11-02,María,Norte,0.16,Ultrabook
22,MacBook Air,Asus,MacBook Air 148,1071.32,3,2025-04-03,Ana,Sur,0.17,Oficina
24,MacBook Air,Xiaomi,MacBook Air 662,711.55,5,2025-03-26,Luis,Norte,0.28,Ultrabook
25,Dell XPS,Samsung,Dell XPS 937,1473.60,7,2025-03-02,Elena,Este,0.11,Gaming
26,MacBook Air,Lenovo,MacBook Air 165,612.07,3,2025-03-10,María,Este,0.18,Ultrabook
29,HP Spectre,HP,HP Spectre 198,818.22,4,2024-07-16,Luis,Este,0.23,Oficina

In [16]:
# Ventas cuyo descuento está entre el 20% y el 40%
df_laptops[(df_laptops['Descuento'] > 0.20) & (df_laptops['Descuento'] < 0.40)]

,Producto,Marca,Modelo,Precio,Cantidad,Fecha_Venta,Vendedor,Region,Descuento,Categoria
0,Dell XPS,Dell,Dell XPS 252,1496.85,3,2024-10-27,Luis,Sur,0.29,Oficina
4,Lenovo ThinkPad,Xiaomi,Lenovo ThinkPad 182,1815.88,8,2024-10-27,Juan,Oeste,0.25,Ultrabook
6,Lenovo ThinkPad,Lenovo,Lenovo ThinkPad 794,1902.15,4,2024-08-17,Luis,Oeste,0.22,Gaming
8,MacBook Air,Dell,MacBook Air 452,1365.76,6,2024-09-26,María,Oeste,0.25,Oficina
9,Lenovo ThinkPad,Dell,Lenovo ThinkPad 610,390.10,1,2025-03-02,Luis,Este,0.28,Ultrabook
13,MacBook Air,Lenovo,MacBook Air 590,112.26,3,2025-04-05,Juan,Sur,0.25,Gaming
19,Asus ZenBook,Apple,Asus ZenBook 748,888.89,2,2025-06-15,Carlos,Este,0.27,Gaming
20,Lenovo ThinkPad,HP,Lenovo ThinkPad 132,616.46,5,2025-05-30,María,Norte,0.24,Gaming
23,HP Spectre,OnePlus,HP Spectre 284,449.60,4,2025-02-23,Diego,Oeste,0.25,Gaming
24,MacBook Air,Xiaomi,MacBook Air 662,711.55,5,2025-03-26,Luis,Norte,0.28,Ultrabook
27,Dell XPS,HP,Dell XPS 523,376.86,8,2024-08-09,Luis,Sur,0.25,Ultrabook
29,HP Spectre,HP,HP Spectre 198,818.22,4,2024-07-16,Luis,Este,0.23,Oficina

In [19]:
#Ventas de laptops de la marca Xiaomi o Dell
df_laptops[(df_laptops['Marca']=='Xiaomi') | (df_laptops['Marca']=='Dell')]

,Producto,Marca,Modelo,Precio,Cantidad,Fecha_Venta,Vendedor,Region,Descuento,Categoria
0,Dell XPS,Dell,Dell XPS 252,1496.85,3,2024-10-27,Luis,Sur,0.29,Oficina
4,Lenovo ThinkPad,Xiaomi,Lenovo ThinkPad 182,1815.88,8,2024-10-27,Juan,Oeste,0.25,Ultrabook
7,HP Spectre,Xiaomi,HP Spectre 270,1267.88,3,2024-08-29,María,Sur,0.15,Gaming
8,MacBook Air,Dell,MacBook Air 452,1365.76,6,2024-09-26,María,Oeste,0.25,Oficina
9,Lenovo ThinkPad,Dell,Lenovo ThinkPad 610,390.10,1,2025-03-02,Luis,Este,0.28,Ultrabook
18,Asus ZenBook,Xiaomi,Asus ZenBook 159,980.60,10,2025-03-11,Elena,Sur,0.01,Ultrabook
24,MacBook Air,Xiaomi,MacBook Air 662,711.55,5,2025-03-26,Luis,Norte,0.28,Ultrabook

In [21]:
#Ventas de laptops de la marca Xiaomi o Dell
df_laptops[df_laptops['Marca'].isin(['Xiaomi', 'Dell'])]

,Producto,Marca,Modelo,Precio,Cantidad,Fecha_Venta,Vendedor,Region,Descuento,Categoria
0,Dell XPS,Dell,Dell XPS 252,1496.85,3,2024-10-27,Luis,Sur,0.29,Oficina
4,Lenovo ThinkPad,Xiaomi,Lenovo ThinkPad 182,1815.88,8,2024-10-27,Juan,Oeste,0.25,Ultrabook
7,HP Spectre,Xiaomi,HP Spectre 270,1267.88,3,2024-08-29,María,Sur,0.15,Gaming
8,MacBook Air,Dell,MacBook Air 452,1365.76,6,2024-09-26,María,Oeste,0.25,Oficina
9,Lenovo ThinkPad,Dell,Lenovo ThinkPad 610,390.10,1,2025-03-02,Luis,Este,0.28,Ultrabook
18,Asus ZenBook,Xiaomi,Asus ZenBook 159,980.60,10,2025-03-11,Elena,Sur,0.01,Ultrabook
24,MacBook Air,Xiaomi,MacBook Air 662,711.55,5,2025-03-26,Luis,Norte,0.28,Ultrabook

PATRONES

In [29]:
# Alojamientos cuyo nombre empieza con la palabra Clean
# Accesor - str convertir un dataframe en un StringFunctions
df_airbnb[df_airbnb['name'].str.startswith('Clean')]  # LIKE 'Clean%'

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
36,11452,Clean and Quiet in Brooklyn,7355,Vt,Brooklyn,Bedford-Stuyvesant,40.68876,-73.94312,Private room,35,60,0,NaN,NaN,1,365
179,45542,Clean and Cozy Harlem Apartment,202249,Campbell,Manhattan,Harlem,40.82374,-73.93730,Entire home/apt,100,2,18,2018-12-17,1.79,1,0
200,53470,Clean and convenient 2BR apartment,204539,Mark,Queens,Ridgewood,40.70234,-73.89816,Private room,140,7,6,2015-10-08,0.06,5,365
219,57297,"Clean & bright 1BR in Cobble Hill, GREAT locat...",199392,S.M.,Brooklyn,Cobble Hill,40.68926,-73.99386,Entire home/apt,159,2,222,2019-06-24,2.12,1,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47751,35899551,"Clean, Elegant luxury and close to everything!",259226302,Karen,Brooklyn,Flatbush,40.63378,-73.95867,Private room,135,3,0,NaN,NaN,1,248
48094,36077537,"Clean, quiet, lux BR in Midtown",10287553,Marie,Manhattan,Hell's Kitchen,40.76843,-73.98940,Private room,147,2,1,2019-07-01,1.00,1,27
48477,36278924,"Clean & Spacious 2 BR in DwnTwn NYC, Walk to U...",272856249,Alex,Manhattan,Gramercy,40.73258,-73.98190,Entire home/apt,300,10,0,NaN,NaN,1,33
48668,36378818,Clean One Bedroom,3449848,V,Manhattan,Chelsea,40.73896,-73.99935,Entire home/apt,350,3,0,NaN,NaN,1,8
48706,36391866,"Clean, modern, and comfy 1bd apt Manhattan-Ha...",273644177,Merce,Manhattan,Harlem,40.80078,-73.95079,Entire home/apt,137,1,0,NaN,NaN,1,35

In [28]:
# Alojamientos cuyo nombre contiene la palabra Home
df_airbnb[df_airbnb['name'].str.contains('Home')]  # LIKE '%Home%'

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
71,17037,Lovely EV Artist's Home,66035,Anna,Manhattan,East Village,40.72162,-73.98008,Entire home/apt,230,9,49,2018-05-14,0.43,1,116
92,20755,"Large Parlor Room, Landmark Home 1 block to PRATT",51038,Erica,Brooklyn,Clinton Hill,40.68634,-73.96600,Private room,98,7,16,2019-05-31,0.20,6,185
95,21293,Sunny Apartment in Artist Home,44145,Tyrome,Brooklyn,Bushwick,40.70093,-73.92609,Entire home/apt,105,3,118,2019-06-18,1.05,2,9
111,26520,"Cozy Room #3, Landmark Home 1 Block to PRATT",51038,Erica,Brooklyn,Clinton Hill,40.68698,-73.96572,Private room,125,2,19,2019-06-02,0.20,6,250
272,64707,Amazing Sunny & Breezy Home In the Heart of NYC,7310,Tilly,Manhattan,Little Italy,40.71702,-73.99811,Entire home/apt,90,14,1,2019-01-02,0.16,1,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48716,36395973,Homely spot for female. Close to subway &Park,156114168,Kateryna,Brooklyn,Prospect-Lefferts Gardens,40.66049,-73.96064,Shared room,40,1,0,NaN,NaN,6,245
48759,36420404,Home Sweet Home,273656890,Liana,Manhattan,East Harlem,40.79266,-73.94740,Private room,50,1,0,NaN,NaN,1,81
48791,36427922,Home away from home,238163900,Lucy,Queens,Cambria Heights,40.68557,-73.72731,Private room,50,3,0,NaN,NaN,1,176
48837,36451481,Feels Like Home,31244206,Pedro,Manhattan,Harlem,40.82385,-73.93947,Private room,80,3,0,NaN,NaN,1,70
48872,36476675,Nycity-MyHome,8636072,Ben,Manhattan,Hell's Kitchen,40.76236,-73.99255,Entire home/apt,260,3,0,NaN,NaN,1,9

In [32]:
# Alojamientos cuyo nombre contiene la palabra Home
# case que ignore las mayusculas
# na que solo analice los registros llenos e ignore los vacios
df_airbnb[df_airbnb['name'].str.contains('Home', case=False, na=False)]  # LIKE '%Home%'

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
37,11708,Cute apt in artist's home,44145,Tyrome,Brooklyn,Bushwick,40.70186,-73.92745,Entire home/apt,85,2,231,2019-06-22,1.96,2,22
71,17037,Lovely EV Artist's Home,66035,Anna,Manhattan,East Village,40.72162,-73.98008,Entire home/apt,230,9,49,2018-05-14,0.43,1,116
92,20755,"Large Parlor Room, Landmark Home 1 block to PRATT",51038,Erica,Brooklyn,Clinton Hill,40.68634,-73.96600,Private room,98,7,16,2019-05-31,0.20,6,185
95,21293,Sunny Apartment in Artist Home,44145,Tyrome,Brooklyn,Bushwick,40.70093,-73.92609,Entire home/apt,105,3,118,2019-06-18,1.05,2,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48716,36395973,Homely spot for female. Close to subway &Park,156114168,Kateryna,Brooklyn,Prospect-Lefferts Gardens,40.66049,-73.96064,Shared room,40,1,0,NaN,NaN,6,245
48759,36420404,Home Sweet Home,273656890,Liana,Manhattan,East Harlem,40.79266,-73.94740,Private room,50,1,0,NaN,NaN,1,81
48791,36427922,Home away from home,238163900,Lucy,Queens,Cambria Heights,40.68557,-73.72731,Private room,50,3,0,NaN,NaN,1,176
48837,36451481,Feels Like Home,31244206,Pedro,Manhattan,Harlem,40.82385,-73.93947,Private room,80,3,0,NaN,NaN,1,70
48872,36476675,Nycity-MyHome,8636072,Ben,Manhattan,Hell's Kitchen,40.76236,-73.99255,Entire home/apt,260,3,0,NaN,NaN,1,9

FUNCIONES DE AGREGACION

In [33]:
# AVG, COUNT, MAX, MIN, SUM funciones de agregación
# Cual es el precio maximo de los alojamientos?
df_airbnb['price'].max()

np.int64(10000)

In [36]:
# Promedio
df_airbnb['price'].mean()

np.float64(152.7206871868289)

In [37]:
# Cuantos alojamientos tiene un precio mayor a 600
df_airbnb[df_airbnb['price'] > 600].count() # ERROR: ESTO DA POR CADA COLUMNA

id                                778
name                              778
host_id                           778
host_name                         778
neighbourhood_group               778
neighbourhood                     778
latitude                          778
longitude                         778
room_type                         778
price                             778
minimum_nights                    778
number_of_reviews                 778
last_review                       449
reviews_per_month                 449
calculated_host_listings_count    778
availability_365                  778
dtype: int64

In [44]:
# Cuantos alojamientos tiene un precio mayor a 600 (COUNT)
(df_airbnb['price'] > 600).sum()

np.int64(778)

In [45]:
# Cuantos alojamientos tiene un precio mayor a 600 (COUNT)
df_airbnb[df_airbnb['price'] > 600].shape[0]

778

In [46]:
# Cuantos alojamientos tiene un precio mayor a 600 (COUNT)
df_airbnb[df_airbnb['price'] > 600]['name'].count()

np.int64(778)

In [50]:
# df[condicion][columnas]
df_airbnb[df_airbnb['price'] > 600][['name', 'price']]

                                                    name  price
85                   perfect for a family or small group    800
345                                 The Brooklyn Waverly    650
496                Luxury 2Bed/2.5Bath Central Park View   2000
653    4 BEDROOM -2BATHRM WEST VILLAGE DUPLEX  TOWNHOUSE    700
662                   Heart & Soul of Greenwich Village     850
...                                                  ...    ...
48523  Tasteful & Trendy Brooklyn Brownstone, near Train   1369
48535     Stunning & Stylish Brooklyn Luxury, near Train   1749
48697         HUGE LUXURY CONDO – INCREDIBLE WATER VIEWS    750
48757     Luxury & Spacious 1500 ft² MANHATTAN Townhouse    700
48839  Massage Spa. Stay overnight. Authors Artist dr...    800

[778 rows x 2 columns]

AGRUPAMIENTO

In [53]:
# groupby
# Cantidad de alojamientos por tipo de habitación
df_airbnb.groupby('room_type').size().reset_index(name='cantidad')

         room_type  cantidad
0  Entire home/apt     25409
1     Private room     22326
2      Shared room      1160