## EN ESTA VERSION DEL EJERCICIO, LOS MISMOS DATOS DE ENTRENAMIENTO SE OCUPARON PARA HACER PRUEBAS.

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
datos = [
    [2450000, 1370000000],
    [2480000, 1350000000],
    [2540000, 1400000000],
    [2420000, 1330000000],
    [2350000, 1270000000],
    [2290000, 1210000000],
    [2400000, 1330000000],
    [2460000, 1350000000]
]
df_datos = pd.DataFrame(datos, columns=['cantidad_turistas', 'dinero gastado'])
df_datos

   cantidad_turistas  dinero gastado
0            2450000      1370000000
1            2480000      1350000000
2            2540000      1400000000
3            2420000      1330000000
4            2350000      1270000000
5            2290000      1210000000
6            2400000      1330000000
7            2460000      1350000000

## Realiza los modelos lineal y polinomial de grado 2. De acuerdo con las métricas vistas en clase, ¿Cuál de los dos modelos se ajusta mejor a los datos?

In [3]:
x_datos = df_datos[['cantidad_turistas']]
y_datos = df_datos[['dinero gastado']]

In [5]:
# Modelos de grado 1 y 2
for i in range(1, 3):
    
    # Se define el gardo
    grado = i
    poly = PolynomialFeatures(degree=grado)
    x_poly = poly.fit_transform(x_datos)
    
    modelo_poly = LinearRegression()
    modelo_poly.fit(x_poly, y_datos)

    # Se realizan las prediciones
    predicciones = modelo_poly.predict(x_poly)

    # Calculo de RSME
    rmse_puntaje = np.sqrt(mean_squared_error(y_datos, predicciones))

    # Calculo de R2
    r2_puntaje = r2_score(y_datos, predicciones)
    
    print(f'predicciones de modelo grado {grado}: ', predicciones)
    print('esperados: ', y_datos)
    print(f'puntaje rsme de modelo grado {grado}: ', rmse_puntaje)
    print(f'puntaje r2 de modelo grado {grado}: ', r2_puntaje)
    print('----------------------------------')

predicciones de modelo grado 1:  [[1.34567361e+09]
 [1.36787203e+09]
 [1.41226886e+09]
 [1.32347520e+09]
 [1.27167890e+09]
 [1.22728207e+09]
 [1.30867625e+09]
 [1.35307308e+09]]
esperados:     dinero gastado
0      1370000000
1      1350000000
2      1400000000
3      1330000000
4      1270000000
5      1210000000
6      1330000000
7      1350000000
puntaje rsme de modelo grado 1:  15288536.886860223
puntaje r2 de modelo grado 1:  0.9257602032306864
----------------------------------
predicciones de modelo grado 2:  [[1.34498723e+09]
 [1.36758882e+09]
 [1.41361719e+09]
 [1.32266072e+09]
 [1.27163524e+09]
 [1.22909108e+09]
 [1.30792919e+09]
 [1.35249053e+09]]
esperados:     dinero gastado
0      1370000000
1      1350000000
2      1400000000
3      1330000000
4      1270000000
5      1210000000
6      1330000000
7      1350000000
puntaje rsme de modelo grado 2:  15948215.300067646
puntaje r2 de modelo grado 2:  0.9192153024294394
----------------------------------

In [6]:
# RESPUESTA = El modelo de regresion polinomica de grado 1 se ajusta mejor a los datos en este caso, debido
# a que su r2 es la mas cercana a 1 (0.9257...) y su rsme es mas cercano a 0 (15288536.8...)

## Aproximadamente, ¿cuánto dinero gastarían en su visita a Cancún 2.5 millones de turistas?

In [14]:
df_dato = pd.DataFrame({
    'cantidad_turistas': [2500000]
})
df_dato

   cantidad_turistas
0            2500000

In [16]:
# Se crea y entrena el modelo de grado 1 usando los DATOS ORIGINALES
poly = PolynomialFeatures(degree=1)
x_poly = poly.fit_transform(x_datos) # Usamos los x_datos de arriba
    
modelo_grado = LinearRegression()
modelo_grado.fit(x_poly, y_datos)    # Entrenamos con los y_datos de arriba

# Transformamos el dato NUEVO (2.5 millones)
df_dato_poly = poly.transform(df_dato)

# Predecimos el dinero usando el modelo de grado 1
predicciones_nuevo = modelo_grado.predict(df_dato_poly)

print('Dinero gastado por 2.5 millones de turistas: $', predicciones_nuevo[0][0])

Dinero gastado por 2.5 millones de turistas: $ 1382670971.5292044