## EN ESTA VERSION DEL EJERCICIO, LOS MISMOS DATOS DE ENTRENAMIENTO SE OCUPARON PARA HACER PRUEBAS

## NOTA: Debido al bajo volumen de datos (8 registros), en esta versión se entrena y se evalúa con el mismo conjunto completo. Advertencia: Esto generará métricas engañosas (R² cercano a 1.0 y RMSE cercano a 0) debido al sobreajuste (overfitting), ya que el modelo simplemente está memorizando los datos en lugar de generalizar el patrón. SE RECOMIENDA OCUPAR PARA ESTE EXAMEN!!

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
datos = [
    [3.5, 10, 7],
    [3.8, 15, 8],
    [2.9, 5, 6],
    [3.2, 8, 6],
    [3.9, 20, 7],
    [2.7, 3, 5],
    [3.6, 12, 8],
    [3.0, 6, 7]
]
df_datos = pd.DataFrame(datos, columns=['calificaciones', 'horas_estudio_semana', 'horas_estudio_noche'])
df_datos

   calificaciones  horas_estudio_semana  horas_estudio_noche
0             3.5                    10                    7
1             3.8                    15                    8
2             2.9                     5                    6
3             3.2                     8                    6
4             3.9                    20                    7
5             2.7                     3                    5
6             3.6                    12                    8
7             3.0                     6                    7

## Realiza los modelos lineal y polinomial de grado 2, 3 y 4. De acuerdo con las métricas vistas en clase, ¿Cuál de los dos modelos se ajusta mejor a los datos?

In [3]:
x_datos = df_datos[['horas_estudio_semana', 'horas_estudio_noche']]
y_datos = df_datos[['calificaciones']]

In [4]:
# lineal
modelo_lineal = LinearRegression()
modelo_lineal.fit(x_datos, y_datos)
predicciones_lineal = modelo_lineal.predict(x_datos)
print('predicciones_lineal: ', predicciones_lineal)
print('esperados: ', y_datos)

predicciones_lineal:  [[3.36148087]
 [3.78032446]
 [2.94263727]
 [3.12458403]
 [3.96797005]
 [2.70574043]
 [3.5983777 ]
 [3.11888519]]
esperados:     calificaciones
0             3.5
1             3.8
2             2.9
3             3.2
4             3.9
5             2.7
6             3.6
7             3.0

In [5]:
# polinomial grado 2
poly2 = PolynomialFeatures(degree=2)
x_poly2 = poly2.fit_transform(x_datos)
modelo_poly2 = LinearRegression()
modelo_poly2.fit(x_poly2, y_datos)
predicciones_poli2 = modelo_poly2.predict(x_poly2)
print('predicciones_poli2: ', predicciones_poli2)
print('esperados: ', y_datos)

predicciones_poli2:  [[3.43617211]
 [3.81959878]
 [2.92013367]
 [3.23946501]
 [3.89706591]
 [2.68013377]
 [3.60026745]
 [3.00716329]]
esperados:     calificaciones
0             3.5
1             3.8
2             2.9
3             3.2
4             3.9
5             2.7
6             3.6
7             3.0

In [6]:
# polinomial grado 3
poly3 = PolynomialFeatures(degree=3)
x_poly3 = poly3.fit_transform(x_datos)
modelo_poly3 = LinearRegression()
modelo_poly3.fit(x_poly3, y_datos)
predicciones_poli3 = modelo_poly3.predict(x_poly3)
print('predicciones_poli3: ', predicciones_poli3)
print('esperados: ', y_datos)

predicciones_poli3:  [[3.5]
 [3.8]
 [2.9]
 [3.2]
 [3.9]
 [2.7]
 [3.6]
 [3. ]]
esperados:     calificaciones
0             3.5
1             3.8
2             2.9
3             3.2
4             3.9
5             2.7
6             3.6
7             3.0

In [7]:
# polinomial grado 4
poly4 = PolynomialFeatures(degree=4)
x_poly4 = poly4.fit_transform(x_datos)
modelo_poly4 = LinearRegression()
modelo_poly4.fit(x_poly4, y_datos)
predicciones_poli4 = modelo_poly4.predict(x_poly4)
print('predicciones_poli4: ', predicciones_poli4)
print('esperados: ', y_datos)

predicciones_poli4:  [[3.5]
 [3.8]
 [2.9]
 [3.2]
 [3.9]
 [2.7]
 [3.6]
 [3. ]]
esperados:     calificaciones
0             3.5
1             3.8
2             2.9
3             3.2
4             3.9
5             2.7
6             3.6
7             3.0

In [8]:
# comparar por rsme
rmse_lineal = np.sqrt(mean_squared_error(y_datos, predicciones_lineal))
rmse_poli2 = np.sqrt(mean_squared_error(y_datos, predicciones_poli2))
rmse_poli3 = np.sqrt(mean_squared_error(y_datos, predicciones_poli3))
rmse_poli4 = np.sqrt(mean_squared_error(y_datos, predicciones_poli4))
print('puntaje rsme lineal: ', rmse_lineal)
print('puntaje rsme poli2: ', rmse_poli2)
print('puntaje rsme poli3: ', rmse_poli3)
print('puntaje rsme poli4: ', rmse_poli4)

puntaje rsme lineal:  0.075721021156117
puntaje rsme poli2:  0.029316428690757554
puntaje rsme poli3:  1.7143511629809197e-14
puntaje rsme poli4:  1.8219162378524126e-14

In [9]:
# Comparar por R2
r2_lineal = r2_score(y_datos, predicciones_lineal)
r2_poli2 = r2_score(y_datos, predicciones_poli2)
r2_poli3 = r2_score(y_datos, predicciones_poli3)
r2_poli4 = r2_score(y_datos, predicciones_poli4)
print('puntaje r2 lineal: ', r2_lineal)
print('puntaje r2 poli2: ', r2_poli2)
print('puntaje r2 poli3: ', r2_poli3)
print('puntaje r2 poli4: ', r2_poli4)

puntaje r2 lineal:  0.9661480558233203
puntaje r2 poli2:  0.9949257387974596
puntaje r2 poli3:  1.0
puntaje r2 poli4:  1.0

In [10]:
# RESPUESTA = El modelo de regresion polinomica de grado 2 se ajusta mejor a los datos en este caso, debido
# a que su r2 es la mas cercana a 1 (0.9949...) y su rsme es mas cercano a 0 (0.0293...)

## ¿Qué promedio obtendría un estudiante que haya estudiado 15 horas a la semana y duerma 5 horas por noche?

In [11]:
df_dato = pd.DataFrame({
    'horas_estudio_semana': [15],
    'horas_estudio_noche': [5]
})
df_dato

   horas_estudio_semana  horas_estudio_noche
0                    15                    5

In [12]:
# Transformamos el dato nuevo con el polinomio de grado 2
df_dato_poly2 = poly2.transform(df_dato)

# Predecimos usando el modelo de grado 2
predicciones_nuevo = modelo_poly2.predict(df_dato_poly2)

print('predicciones de 15 horas semana y 5 horas por noche: ', predicciones_nuevo[0][0])

predicciones de 15 horas semana y 5 horas por noche:  3.528355774435309