## EN ESTA VERSION DEL EJERCICIO, SE DIVIDIERON LOS DATOS ENTRE ENTRENAMIENTO Y PRUEBA

## NOTA: Al tener un dataset tan pequeño (8 registros), dividir los datos en entrenamiento y prueba deja solo 2 registros para evaluar. Esto provoca inestabilidad matemática en los modelos polinomiales de grados altos, resultando en un severo sobreajuste (R² negativos y RMSE altos en las pruebas). NO SE RECOMIENDA OCUPAR ESTE PARA EL EXAMEN!!

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
datos = [
    [3.5, 10, 7],
    [3.8, 15, 8],
    [2.9, 5, 6],
    [3.2, 8, 6],
    [3.9, 20, 7],
    [2.7, 3, 5],
    [3.6, 12, 8],
    [3.0, 6, 7]
]
df_datos = pd.DataFrame(datos, columns=['calificaciones', 'horas_estudio_semana', 'horas_estudio_noche'])
df_datos

   calificaciones  horas_estudio_semana  horas_estudio_noche
0             3.5                    10                    7
1             3.8                    15                    8
2             2.9                     5                    6
3             3.2                     8                    6
4             3.9                    20                    7
5             2.7                     3                    5
6             3.6                    12                    8
7             3.0                     6                    7

## Realiza los modelos lineal y polinomial de grado 2, 3 y 4. De acuerdo con las métricas vistas en clase, ¿Cuál de los dos modelos se ajusta mejor a los datos?

In [3]:
x_datos = df_datos[['horas_estudio_semana', 'horas_estudio_noche']]
y_datos = df_datos[['calificaciones']]

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x_datos, y_datos, test_size=0.2, random_state=42)

In [5]:
# lineal
modelo_lineal = LinearRegression()
modelo_lineal.fit(x_train, y_train)
predicciones_lineal = modelo_lineal.predict(x_test)
print('predicciones_lineal: ', predicciones_lineal)
print('esperados: ', y_test)

predicciones_lineal:  [[3.76396841]
 [2.72537019]]
esperados:     calificaciones
1             3.8
5             2.7

In [6]:
# polinomial grado 2
poly2 = PolynomialFeatures(degree=2)
x_train_poly2 = poly2.fit_transform(x_train)
x_test_poly2 = poly2.transform(x_test)
modelo_poly2 = LinearRegression()
modelo_poly2.fit(x_train_poly2, y_train)
predicciones_poli2 = modelo_poly2.predict(x_test_poly2)
print('predicciones_poli2: ', predicciones_poli2)
print('esperados: ', y_test)

predicciones_poli2:  [[3.90428571]
 [2.45678571]]
esperados:     calificaciones
1             3.8
5             2.7

In [7]:
# polinomial grado 3
poly3 = PolynomialFeatures(degree=3)
x_train_poly3 = poly3.fit_transform(x_train)
x_test_poly3 = poly3.transform(x_test)
modelo_poly3 = LinearRegression()
modelo_poly3.fit(x_train_poly3, y_train)
predicciones_poli3 = modelo_poly3.predict(x_test_poly3)
print('predicciones_poli3: ', predicciones_poli3)
print('esperados: ', y_test)

predicciones_poli3:  [[4.80781342]
 [2.80952989]]
esperados:     calificaciones
1             3.8
5             2.7

In [8]:
# polinomial grado 4
poly4 = PolynomialFeatures(degree=4)
x_train_poly4 = poly4.fit_transform(x_train)
x_test_poly4 = poly4.transform(x_test)
modelo_poly4 = LinearRegression()
modelo_poly4.fit(x_train_poly4, y_train)
predicciones_poli4 = modelo_poly4.predict(x_test_poly4)
print('predicciones_poli3: ', predicciones_poli4)
print('esperados: ', y_test)

predicciones_poli3:  [[5.42784111]
 [2.83574015]]
esperados:     calificaciones
1             3.8
5             2.7

In [9]:
# comparar por rsme
rmse_lineal = np.sqrt(mean_squared_error(y_test, predicciones_lineal))
rmse_poli2 = np.sqrt(mean_squared_error(y_test, predicciones_poli2))
rmse_poli3 = np.sqrt(mean_squared_error(y_test, predicciones_poli3))
rmse_poli4 = np.sqrt(mean_squared_error(y_test, predicciones_poli4))
print('puntaje rsme lineal: ', rmse_lineal)
print('puntaje rsme poli2: ', rmse_poli2)
print('puntaje rsme poli3: ', rmse_poli3)
print('puntaje rsme poli4: ', rmse_poli4)

puntaje rsme lineal:  0.03116024588462889
puntaje rsme poli2:  0.18712121603333756
puntaje rsme poli3:  0.7168279717324432
puntaje rsme poli4:  1.1550523968200461

In [10]:
# Comparar por R2
r2_lineal = r2_score(y_test, predicciones_lineal)
r2_poli2 = r2_score(y_test, predicciones_poli2)
r2_poli3 = r2_score(y_test, predicciones_poli3)
r2_poli4 = r2_score(y_test, predicciones_poli4)
print('puntaje r2 lineal: ', r2_lineal)
print('puntaje r2 poli2: ', r2_poli2)
print('puntaje r2 poli3: ', r2_poli3)
print('puntaje r2 poli4: ', r2_poli4)

puntaje r2 lineal:  0.9967902118228412
puntaje r2 poli2:  0.8842500843312562
puntaje r2 poli3:  -0.6986523671340452
puntaje r2 poli4:  -3.410400130247056

In [11]:
# RESPUESTA = El modelo de regresion polinomica de grado 1 se ajusta mejor a los datos en este caso, debido
# a que su r2 es la mas cercana a 1 (0.9967...) y su rsme es mas cercano a 0 (0.0311...)

## ¿Qué promedio obtendría un estudiante que haya estudiado 15 horas a la semana y duerma 5 horas por noche?

In [12]:
df_dato = pd.DataFrame({
    'horas_estudio_semana': [15],
    'horas_estudio_noche': [5]
})
df_dato

   horas_estudio_semana  horas_estudio_noche
0                    15                    5

In [13]:
predicciones_lineal = modelo_lineal.predict(df_dato)
print('predicciones de 15 horas semana y 5 horas por noche: ', predicciones_lineal[0][0])

predicciones de 15 horas semana y 5 horas por noche:  3.4503455083909182